name: marp-to-pages
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fix permissions

      - name: Marp Build
        uses: docker://marpteam/marp-cli:v1.7.0
        with:
          args: README.md -o build/index.html
        env:
          MARP_USER: root:root

      - name: Deploy production
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./build/
          clean-exclude: pr-preview/

