name: marp-to-pages
concurrency: preview-${{ github.ref }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  build:
    container:
      image: marpteam/marp-cli:v1.7.0
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Marp Build
        run: node /home/marp/.cli/marp-cli.js README.md -o build/index.html

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build/
          preview-branch: gh-pages
          umbrella-dir: pr-preview

